import 'package:tiktok_clone/app/utils/strings.dart';

class AuthErrors {
  static const errorMessages = {
    Strings.AUTH_ERROR_API_NOT_AVAILABLE: 'API indisponível',
    Strings.AUTH_ERROR_UNKNOWN: 'Erro desconhecido',
    Strings.AUTH_ERROR_INVALID_CUSTOM_TOKEN: 'Custom token inválido',
    Strings.AUTH_ERROR_CUSTOM_TOKEN_MISMATCH: 'Custom token não confere',
    Strings.AUTH_ERROR_INVALID_CREDENTIAL: 'Credencial inválida',
    Strings.AUTH_ERROR_USER_DISABLED: 'Usuário desabilitado',
    Strings.AUTH_ERROR_OPERATION_NOT_ALLOWED: 'Operação não permitida',
    Strings.AUTH_ERROR_EMAIL_ALREADY_IN_USE: 'O email informado já está cadastrado no Mangos.',
    Strings.AUTH_ERROR_INVALID_EMAIL: 'O email informado é inválido.',
    Strings.AUTH_ERROR_WRONG_PASSWORD: 'A senha informada está incorreta.',
    Strings.AUTH_ERROR_TOO_MANY_REQUESTS: 'Excesso de requisições',
    Strings.AUTH_ERROR_USER_NOT_FOUND: 'O usuário não foi encontrado',
    Strings.AUTH_ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL: 'Esta conta existe com outra credencial',
    Strings.AUTH_ERROR_REQUIRES_RECENT_LOGIN:
        'Esta ação requer um login recente. Faça o login novamente e repita o processo',
    Strings.AUTH_ERROR_PROVIDER_ALREADY_LINKED: 'Provedor já conectado',
    Strings.AUTH_ERROR_NO_SUCH_PROVIDER: 'Provedor desconhecido',
    Strings.AUTH_ERROR_INVALID_USER_TOKEN: 'Token de usuário inválido',
    Strings.AUTH_ERROR_NETWORK_REQUEST_FAILED: 'Falha no acesso à rede',
    Strings.AUTH_ERROR_USER_TOKEN_EXPIRED: 'Token de usuário expirado',
    Strings.AUTH_ERROR_INVALID_API_KEY: 'Chave de API inválida',
    Strings.AUTH_ERROR_USER_MISMATCH: 'Usuário não confere',
    Strings.AUTH_ERROR_CREDENTIAL_ALREADY_IN_USE: 'Credencial em uso',
    Strings.AUTH_ERROR_WEAK_PASSWORD: 'A senha informada é muito simples',
    Strings.AUTH_ERROR_APP_NOT_AUTHORIZED: 'Aplicativo não autorizado',
    Strings.AUTH_ERROR_EXPIRED_ACTION_CODE: 'Código de ação expirado',
    Strings.AUTH_ERROR_INVALID_ACTION_CODE: 'Código de ação inválido',
    Strings.AUTH_ERROR_INVALID_MESSAGE_PAYLOAD: 'Payload de mensagem inválido',
    Strings.AUTH_ERROR_INVALID_SENDER: 'Remetente inválido',
    Strings.AUTH_ERROR_INVALID_RECIPIENT_EMAIL: 'E-mail de destinatário inválido',
    Strings.AUTH_ERROR_MISSING_EMAIL: 'E-mail ausente',
    Strings.AUTH_ERROR_MISSING_PASSWORD: 'Senha ausente',
    Strings.AUTH_ERROR_MISSING_IOS_BUNDLE_ID: 'Bundle ID do iOS ausente',
    Strings.AUTH_ERROR_MISSING_ANDROID_PKG_NAME: 'Nome de pacote Android ausente',
    Strings.AUTH_ERROR_UNAUTHORIZED_DOMAIN: 'Domínio não autorizado',
    Strings.AUTH_ERROR_INVALID_CONTINUE_URI: 'URI de continuação inválida',
    Strings.AUTH_ERROR_MISSING_CONTINUE_URI: 'URI de continuação ausente',
    Strings.AUTH_ERROR_MISSING_PHONE_NUMBER: 'Número de telefone ausente',
    Strings.AUTH_ERROR_INVALID_PHONE_NUMBER: 'Número de telefone inválido',
    Strings.AUTH_ERROR_MISSING_VERIFICATION_CODE: 'Código de verificação ausente',
    Strings.AUTH_ERROR_INVALID_VERIFICATION_CODE: 'Código de verificação inválido',
    Strings.AUTH_ERROR_MISSING_VERIFICATION_ID: 'ID de verificação ausente',
    Strings.AUTH_ERROR_INVALID_VERIFICATION_ID: 'ID de verificação inválido',
    Strings.AUTH_MISSING_APP_CREDENTIAL: 'Credencial do aplicativo ausente',
    Strings.AUTH_INVALID_APP_CREDENTIAL: 'Credencial do aplicactivo inválida',
    Strings.AUTH_ERROR_SESSION_EXPIRED: 'Sessão expirada',
    Strings.AUTH_ERROR_QUOTA_EXCEEDED: 'Cota excedida',
    Strings.AUTH_ERROR_MISSING_APP_TOKEN: 'Token do aplicativo ausente',
    Strings.AUTH_ERROR_NOTIFICATION_NOT_FORWARDED: 'Notificação não repassada',
    Strings.AUTH_ERROR_APP_NOT_VERIFIED: 'Aplicativo não verificado',
    Strings.AUTH_ERROR_CAPTCHA_CHECK_FAILED: 'Falha de verificação de captcha',
    Strings.AUTH_ERROR_WEB_CONTEXT_ALREADY_PRESENTED: 'Contexto da web já existe',
    Strings.AUTH_ERROR_WEB_CONTEXT_CANCELLED: 'Contexto da web cancelado',
    Strings.AUTH_ERROR_APP_VERIFICATION_FAILED: 'Falha na verificação de aplicativo',
    Strings.AUTH_ERROR_INVALID_CLIENT_ID: 'ID de cliente inválido',
    Strings.AUTH_ERROR_WEB_NETWORK_REQUEST_FAILED: 'A requisição de rede da web falhou',
    Strings.AUTH_ERROR_WEB_INTERNAL_ERROR: 'Erro interno da web',
    Strings.AUTH_ERROR_NULL_USER: 'Usuário nulo',
    Strings.AUTH_ERROR_KEYCHAIN_ERROR: 'Erro de Keychain',
    Strings.AUTH_ERROR_INTERNAL_ERROR: 'Erro interno',
    Strings.AUTH_ERROR_MALFORMED_JWT: 'Formato inválido de JWT',
    Strings.AUTH_ERROR_SIGN_IN_FAILED: 'Erro ao entrar',
  };
}
